# A string used to distinguish different Supabase projects on the same host. Defaults to the workspace name when running locally.
project_id = "bloved"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
# public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returned from a table or view. Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's major version.
# Options: 15, 14, 13, 12, 11
major_version = 17

[db.pooler]
enabled = false
# Port to use for the local connection pooler.
port = 54329
# Specifies when a server connection can be reused by other clients.
# Options: transaction, session
pool_mode = "transaction"
# How many server connections to allow per user/database pair.
default_pool_size = 15
# Maximum number of client connections allowed.
max_client_conn = 100

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: IPv4)
# ip_version = "IPv4"

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost:54321"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (one week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses.
# If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false
# Template for sending SMS messages.
# template = "Your code is {{ .Code }}"

# Use secrets to store sensitive configuration values.
# Run `supabase secrets set --env-file ./supabase/.env.local` to set secrets from a .env file.
# Run `supabase secrets list` to list all secrets.
# Learn more: https://supabase.com/docs/guides/cli/config#secrets

# Edge Functions configuration
[functions.signup]
enabled = true
verify_jwt = false
entrypoint = "./functions/signup/index.ts"

[functions.check-dog-registration]
enabled = true
verify_jwt = false
entrypoint = "./functions/check-dog-registration/index.ts"

[functions.get-available-times]
enabled = true
verify_jwt = true
entrypoint = "./functions/get-available-times/index.ts"

[functions.get-dog-appointments]
enabled = true
verify_jwt = true
entrypoint = "./functions/get-dog-appointments/index.ts"

[functions.reserve-appointment]
enabled = true
verify_jwt = true
entrypoint = "./functions/reserve-appointment/index.ts"


[functions.get-client-subscriptions]
enabled = true
verify_jwt = true
entrypoint = "./functions/get-client-subscriptions/index.ts"

[functions.get-card-usage]
enabled = true
verify_jwt = true
entrypoint = "./functions/get-card-usage/index.ts"

[functions.get-subscription-types]
enabled = true
verify_jwt = true
entrypoint = "./functions/get-subscription-types/index.ts"

[functions.move-appointment]
enabled = true
verify_jwt = true
entrypoint = "./functions/move-appointment/index.ts"

[functions.get-group-appointments]
enabled = true
verify_jwt = true
entrypoint = "./functions/get-group-appointments/index.ts"

[functions.duplicate-appointment]
enabled = true
verify_jwt = true
entrypoint = "./functions/duplicate-appointment/index.ts"

[functions.get-breed-pricing]
enabled = true
verify_jwt = false
entrypoint = "./functions/get-breed-pricing/index.ts"

[functions.save-appointment-price]
enabled = true
verify_jwt = false
entrypoint = "./functions/save-appointment-price/index.ts"

[functions.search-products]
enabled = true
verify_jwt = false
entrypoint = "./functions/search-products/index.ts"

[functions.create-customer]
enabled = true
verify_jwt = true
entrypoint = "./functions/create-customer/index.ts"

[functions.book-proposed-meeting]
enabled = true
verify_jwt = true
entrypoint = "./functions/book-proposed-meeting/index.ts"

[functions.create-manager-appointment]
enabled = true
verify_jwt = true
entrypoint = "./functions/create-manager-appointment/index.ts"

[functions.get-active-cart]
enabled = true
verify_jwt = true
entrypoint = "./functions/get-active-cart/index.ts"

[functions.get-pending-appointment-requests]
enabled = true
verify_jwt = true
entrypoint = "./functions/get-pending-appointment-requests/index.ts"

[functions.get-proposed-meeting]
enabled = true
verify_jwt = false
entrypoint = "./functions/get-proposed-meeting/index.ts"

[functions.register-worker]
enabled = true
verify_jwt = true
entrypoint = "./functions/register-worker/index.ts"

[functions.save-cart]
enabled = true
verify_jwt = true
entrypoint = "./functions/save-cart/index.ts"

[functions.search-manager-schedule]
enabled = true
verify_jwt = true
entrypoint = "./functions/search-manager-schedule/index.ts"

[functions.send-payment-request]
enabled = true
verify_jwt = true
entrypoint = "./functions/send-payment-request/index.ts"


